{
 "title": "Minecraft",
 "description": "Fully-featured metrics collection agent for Minecraft servers.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "server",
    "query": "import \"influxdata/influxdb/v1\"\r\n\r\nv1.measurementTagValues(\r\n  bucket: \"${bucket}\",\r\n  measurement: \"minecraft_players_count\",\r\n  tag: \"server\"\r\n)"
   },
   {
    "name": "interval",
    "query": "5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "world",
    "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_world_players_count\" and r.server =~ /^${server:pipe}$/)\r\n  |> keyValues(keyColumns: [\"world\"])\r\n  |> group()\r\n  |> keep(columns: [\"world\"])"
   },
   { "name": "bucket", "label": "Bucket", "query": "minecraft" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime (Mean)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time()-avg(process_start_time_seconds{instance=~\"$instance\",job=\"$job\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "currentSeconds = (int(v: now()) / 1000000000)\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"process_start_time_seconds\" and r.server =~ /^${server:pipe}$/)\r\n  |> last()\r\n  |> group()\r\n  |> map(fn: (r) => ({ r with _value: currentSeconds - int(v: r._value) }))\r\n  |> mean()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_players_count\" and r.server =~ /^${server:pipe}$/)\r\n  |> last()\r\n  |> group()\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_world_entities_count{instance=~\"$instance\",job=~\"$job\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_world_entities_count\" and r.server =~ /^${server:pipe}$/)\r\n  |> last()\r\n  |> group()\r\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_world_loaded_chunks{instance=~\"$instance\",job=~\"$job\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_world_loaded_chunks\" and r.server =~ /^${server:pipe}$/)\r\n  |> last()\r\n  |> group()\r\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TPS (Mean)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(minecraft_tps{instance=~\"$instance\",job=~\"$job\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_tick_duration_seconds\" and r._field == \"count\" and r.server =~ /^${server:pipe}$/)\r\n  |> derivative(unit: 1s)\r\n  |> last()\r\n  |> group()\r\n  |> mean()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MSPT (Mean)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(minecraft_tick_duration_seconds{instance=~\"$instance\",job=~\"$job\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\r\n\r\ndoQuantile = (tables=<-, q) => tables\r\n  |> histogramQuantile(quantile: q)\r\n  |> duplicate(as: \"_time\", column: \"_stop\")\r\n  |> window(every: inf)\r\n  |> map(fn: (r) => ({r with _measurement: \"quantile\", _field: string(v: q)}))\r\n  |> experimental.group(mode: \"extend\", columns: [\"_measurement\", \"_field\"])\r\n\r\nhistograms =\r\n  from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_tick_duration_seconds\" and r._field != \"count\" and r._field != \"sum\" and r.server =~ /^${server:pipe}$/)\r\n  |> aggregateWindow(fn: last, every: v.windowPeriod)\r\n  |> difference(nonNegative: true)\r\n  |> filter(fn: (r) => exists r._value)\r\n  |> group(columns: [\"_field\"])\r\n  |> window(every: v.windowPeriod)\r\n  |> sum()\r\n  |> map(fn: (r) => ({r with le: float(v: r._field)}))\r\n  |> drop(columns: [\"_field\"])\r\n\r\nhistograms |> doQuantile(q: 0.5)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load (Total)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_load_ratio{instance=~\"$instance\",job=~\"$job\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"process_cpu_load_ratio\" and r.server =~ /^${server:pipe}$/)\r\n  |> last()\r\n  |> group()\r\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory (Total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jvm_memory_bytes_used\" and r.server =~ /^${server:pipe}$/)\r\n  |> last()\r\n  |> group()\r\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "$server: minecraft_tps",
     "expr": "minecraft_tps{instance=~\"$instance\",job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_tick_duration_seconds\" and r._field == \"count\" and r.server =~ /^${server:pipe}$/)\r\n  |> derivative(unit: 1s)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: (tables=<-, column) => tables)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MSPT",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$server: minecraft_tick_duration_seconds",
     "expr": "minecraft_tick_duration_seconds{instance=~\"$instance\",job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\r\n\r\ndoQuantile = (tables=<-, q) => tables\r\n  |> histogramQuantile(quantile: q)\r\n  |> duplicate(as: \"_time\", column: \"_stop\")\r\n  |> window(every: inf)\r\n  |> map(fn: (r) => ({r with _measurement: \"quantile\", _field: string(v: q)}))\r\n  |> experimental.group(mode: \"extend\", columns: [\"_measurement\", \"_field\"])\r\n\r\nhistograms =\r\n  from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_tick_duration_seconds\" and r._field != \"count\" and r._field != \"sum\" and r.server =~ /^${server:pipe}$/)\r\n  |> aggregateWindow(fn: last, every: v.windowPeriod)\r\n  |> difference(nonNegative: true)\r\n  |> filter(fn: (r) => exists r._value)\r\n  |> group(columns: [\"_field\"])\r\n  |> window(every: v.windowPeriod)\r\n  |> sum()\r\n  |> map(fn: (r) => ({r with le: float(v: r._field)}))\r\n  |> drop(columns: [\"_field\"])\r\n\r\nunion(tables: [\r\n  histograms |> doQuantile(q: 0.99),\r\n  histograms |> doQuantile(q: 0.95),\r\n  histograms |> doQuantile(q: 0.75),\r\n  histograms |> doQuantile(q: 0.5),\r\n])\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$server: minecraft_players_count",
     "expr": "minecraft_players_count{instance=~\"$instance\",job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_players_count\" and r.server =~ /^${server:pipe}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Player flow",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "alias": "events: join",
     "expr": "sum(increase(minecraft_events_join_total{instance=~\"$instance\",job=~\"$job\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "events: join",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_players_count\" and r.server =~ /^${server:pipe}$/)\r\n  |> difference()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "World [$world]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }, "repeat": "world" },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "world: chunks",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_world_loaded_chunks\" and r.server =~ /^${server:pipe}$/ and r.world =~ /^${world:pipe}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "world: entities",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_world_entities_count\" and r.server =~ /^${server:pipe}$/ and r.world =~ /^${world:pipe}$/)\r\n  |> map(fn: (r) => ({ r with _field: \"players: ${r.server}\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "world: entities",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"minecraft_world_players_count\" and r.server =~ /^${server:pipe}$/ and r.name =~ /^${world:pipe}$/)\r\n  |> map(fn: (r) => ({ r with _field: \"entities: ${r.server}\" }))\r\n  |> aggregateWindow(every: ${interval}, fn: (tables=<-, column) => tables)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "JVM: Computation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 561 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 562 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$server: process_cpu_load_ratio",
     "expr": "process_cpu_load_ratio{instance=~\"$instance\",job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"process_cpu_load_ratio\" and r.server =~ /^${server:pipe}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Time (per second)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 562 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$server: process_cpu_seconds_total",
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "process_cpu_seconds_total{instance=''{{instance}}\", job=\"{{job}}\"}",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"process_cpu_seconds_total\" and r.server =~ /^${server:pipe}$/)\r\n  |> derivative(unit: 1s)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: (tables=<-, column) => tables)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 573 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$server: jvm_threads_current_count",
     "expr": "jvm_threads_current_count{instance=~\"$instance\",job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jvm_threads_current_count\" and r.server =~ /^${server:pipe}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daemons",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 573 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$server: jvm_threads_current_count",
     "expr": "jvm_threads_current_count{instance=~\"$instance\",job=~\"$job\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jvm_threads_daemon_count\" and r.server =~ /^${server:pipe}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads started",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 573 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "threads: started",
     "expr": "sum(increase(jvm_threads_started_total{instance=~\"$instance\",job=~\"$job\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "jvm_threads_started_total",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jvm_threads_started_total\" and r.server =~ /^${server:pipe}$/)\r\n  |> difference()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "JVM: Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 584 } },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 585 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "memory: used",
     "expr": "sum(jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "memory: used",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jvm_memory_bytes_used\" and r.server =~ /^${server:pipe}$/ and r.area == \"heap\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Non-heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 585 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "nonheap: used",
     "expr": "sum(jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\",area=\"heap\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "heap: used",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jvm_memory_bytes_used\" and r.server =~ /^${server:pipe}$/ and r.area == \"nonheap\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC Duration (Total)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 596 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "threads: started",
     "expr": "sum(increase(jvm_threads_started_total{instance=~\"$instance\",job=~\"$job\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "jvm_threads_started_total",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jvm_gc_duration_seconds\" and r._field == \"sum\" and r.server =~ /^${server:pipe}$/)\r\n  |> group(columns: [\"gc\"])\r\n  |> difference()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC Freed (Total)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 596 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "threads: started",
     "expr": "sum(increase(jvm_threads_started_total{instance=~\"$instance\",job=~\"$job\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "jvm_threads_started_total",
     "query": " from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"jvm_gc_freed_bytes\" and r._field == \"sum\" and r.server =~ /^${server:pipe}$/)\r\n  |> group(columns: [\"gc\"])\r\n  |> difference()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}