{
 "title": "Systems",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(system_uptime, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Systemd Failed Units", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "${host}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "repeat": "host",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(systemd_units_active_code{host=~\"$host\", active=\"failed\"}) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(systemd_units_active_code{host=~\"$host\", active=~\"reloading|activating|deactivating\"}) or vector(0)",
     "legendFormat": "Jobs"
    }
   ]
  },
  { "title": "Host ${host}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "host" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Systemd Units",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(systemd_units_active_code{host=~\"$host\", active=\"failed\"}) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(systemd_units_active_code{host=~\"$host\", active=~\"reloading|activating|deactivating\"}) or vector(0)",
     "legendFormat": "Jobs"
    }
   ]
  },
  {
   "title": "CPU Usage (Total)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=~\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Load (1m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load1{host=~\"$host\"}",
     "legendFormat": "load1"
    }
   ]
  },
  {
   "title": "Load (5m)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load5{host=~\"$host\"}",
     "legendFormat": "load5"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "processes_running{host=~\"$host\"}",
     "legendFormat": "running"
    },
    {
     "expr": "processes_blocked{host=~\"$host\"}",
     "legendFormat": "blocked"
    },
    {
     "expr": "processes_idle{host=~\"$host\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "processes_unknown{host=~\"$host\"}",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "Load (15m)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load15{host=~\"$host\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_used{host=~\"$host\"}",
     "legendFormat": "used"
    },
    {
     "expr": "mem_buffered{host=~\"$host\"}",
     "legendFormat": "buffered"
    },
    {
     "expr": "mem_cached{host=~\"$host\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "mem_free{host=~\"$host\"}",
     "legendFormat": "free"
    },
    {
     "expr": "mem_swap_cached{host=~\"$host\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "mem_total{host=~\"$host\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=~\"$host\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(net_bytes_recv{host=~\"$host\", interface!=\"all\"}[$__rate_interval])",
     "legendFormat": "receive"
    },
    {
     "expr": "-rate(net_bytes_sent{host=~\"$host\", interface!=\"all\"}[$__rate_interval])",
     "legendFormat": "send"
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sensors_temp_input{host=~\"$host\"}",
     "legendFormat": "{{chip}}"
    }
   ]
  },
  {
   "title": "CPU Usage TopK",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, max by (process_name) (procstat_cpu_usage_topk_aggregate{host=~\"$host\"}))",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Memory RSS TopK",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, max by (process_name) (procstat_memory_rss_topk_aggregate{host=~\"$host\"}))",
     "legendFormat": "{{process_name}}"
    }
   ]
  }
 ]
}