# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  ligature-el = {
    pname = "ligature-el";
    version = "c0e696a88824be6afa1f33fad548d36f96801d8e";
    src = fetchgit {
      url = "https://github.com/mickeynp/ligature.el";
      rev = "c0e696a88824be6afa1f33fad548d36f96801d8e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6D6zrrE2uRk02t9vbTmpMnDFeMAsEqKonEyCDyRvZ4I=";
    };
  };
}
