{ config, ... }:

let
  certDir = config.security.acme.certs."nuc.li7g.com".directory;
in
{
  services.maddy = {
    enable = true;
    hostname = "smtp.li7g.com";
    primaryDomain = "li7g.com";
    localDomains = [ "$(primary_domain)" ];
    config = ''
      # Local storage & authentication

      auth.pam pam_auth {
        debug no
        use_helper no
      }

      tls file ${certDir}/fullchain.pem ${certDir}/key.pem

      # SMTP endpoints + message routing

      # hostname already set by nixos configuration

      table.chain local_rewrites {
        optional_step regexp "(.+)\+(.+)@(.+)" "$1@$3"
        optional_step static {
          entry postmaster postmaster@$(primary_domain)
        }
      }

      submission tls://0.0.0.0:465 tcp://0.0.0.0:587 {
        limits {
          # Up to 50 msgs/sec across any amount of SMTP connections.
          all rate 50 1s
        }

        auth &pam_auth

        source $(local_domains) {
          check {
            authorize_sender {
              prepare_email &local_rewrites
              user_to_email identity
            }
          }

          default_destination {
            modify {
              dkim $(primary_domain) $(local_domains) default
            }
            deliver_to &remote_queue
          }
        }
        default_source {
          reject 501 5.1.8 "Non-local sender domain"
        }
      }

      target.remote outbound_delivery {
        limits {
          # Up to 20 msgs/sec across max. 10 SMTP connections
          # for each recipient domain.
          destination rate 20 1s
          destination concurrency 10
        }
        mx_auth {
          dane
          mtasts {
            cache fs
            fs_dir mtasts_cache/
          }
          local_policy {
            min_tls_level encrypted
            min_mx_level none
          }
        }
      }

      target.queue remote_queue {
        target &outbound_delivery

        autogenerated_msg_domain $(primary_domain)
        bounce {
          default_destination {
            reject 550 5.0.0 "Refusing to send DSNs to non-local addresses"
          }
        }
      }
    '';
  };
  systemd.tmpfiles.rules = [
    "a+ ${certDir}               - - - - user:maddy:r-x"
    "A+ ${certDir}/fullchain.pem - - - - user:maddy:r--"
    "A+ ${certDir}/key.pem       - - - - user:maddy:r--"
  ];
}
